services:
  solr:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        BUILDER_BASE_IMAGE: debian:trixie
        JAVA_RUNTIME_PACKAGE: openjdk-21-jre-headless
        RUNTIME_BASE_IMAGE: debian:trixie
        SOLR_PACKAGE: slim
        SOLR_VERSION: 9.8.1
    image: solr-binary:9.8.1-slim-trixie
    ports:
     - "8983:8983"
    volumes:
      - solr_data:/var/solr/data
      - ./configsets:/opt/solr/server/solr/configsets
volumes:
  solr_data: